#@!out=/etc/auros/grub-theme.cfg mode=0644
# Generated by aurora — GRUB2 theming fragment, spliced into grub.cfg
# by the image builder so even the bootloader follows the active theme.
#
# GRUB2 rather than syslinux is a Secure Boot requirement, not a
# preference: the shim review board has experience only with GRUB2 and
# systemd-boot, and shim's DEFAULT_LOADER expects grubx64.efi. See
# docs/research/signing-trust.md.

set menu_color_normal=white/black
set menu_color_highlight=black/light-cyan
set color_normal=light-gray/black
set color_highlight=black/light-cyan

# Theme-derived values consumed by the GRUB gfxmenu theme file.
set auros_theme_name="@theme_name@"
set auros_bg="@bg|hex@"
set auros_fg="@fg|hex@"
set auros_accent="@accent|hex@"
set auros_muted="@muted|hex@"
set auros_font_size="@font_size|int@"

# No gfxmode and no `terminal_output gfxterm`: the menu stays on the
# firmware's text console, which is what Secure Boot leaves working
# (rootfs/usr/lib/auros/grub.cfg.in says why). The colours above apply
# to it.

set timeout_style=menu
set timeout=5
