#@!out=/etc/auros/colors.sh mode=0644
# Generated by aurora — sourceable palette for shell scripts.
# Usage:  . /etc/auros/colors.sh ;  printf "${C_ACCENT}hi${C_RESET}\n"
AUROS_THEME="@theme_name@"
AUROS_VARIANT="@theme_variant@"

HEX_BG="@bg@";            HEX_BG_ALT="@bg_alt@"
HEX_SURFACE="@surface@";  HEX_SURFACE_HI="@surface_hi@"
HEX_OVERLAY="@overlay@";  HEX_MUTED="@muted@"
HEX_SUBTLE="@subtle@";    HEX_FG="@fg@";  HEX_FG_HI="@fg_hi@"
HEX_ACCENT="@accent@";    HEX_ACCENT_ALT="@accent_alt@"
HEX_ACCENT_WARM="@accent_warm@"
HEX_OK="@ok@";  HEX_WARN="@warn@";  HEX_ERR="@err@";  HEX_INFO="@info@"

# Truecolor SGR sequences, ready to print.
C_RESET="$(printf '\033[0m')"
C_BOLD="$(printf '\033[1m')"
C_DIM="$(printf '\033[2m')"
C_FG="$(printf '\033[38;2;@fg|rgbsp@m'       | tr ' ' ';')"
C_FG_HI="$(printf '\033[38;2;@fg_hi|rgbsp@m' | tr ' ' ';')"
C_SUBTLE="$(printf '\033[38;2;@subtle|rgbsp@m' | tr ' ' ';')"
C_MUTED="$(printf '\033[38;2;@muted|rgbsp@m' | tr ' ' ';')"
C_ACCENT="$(printf '\033[38;2;@accent|rgbsp@m' | tr ' ' ';')"
C_ACCENT_ALT="$(printf '\033[38;2;@accent_alt|rgbsp@m' | tr ' ' ';')"
C_ACCENT_WARM="$(printf '\033[38;2;@accent_warm|rgbsp@m' | tr ' ' ';')"
C_OK="$(printf '\033[38;2;@ok|rgbsp@m'     | tr ' ' ';')"
C_WARN="$(printf '\033[38;2;@warn|rgbsp@m' | tr ' ' ';')"
C_ERR="$(printf '\033[38;2;@err|rgbsp@m'   | tr ' ' ';')"
C_INFO="$(printf '\033[38;2;@info|rgbsp@m' | tr ' ' ';')"
B_SURFACE="$(printf '\033[48;2;@surface|rgbsp@m' | tr ' ' ';')"
B_ACCENT="$(printf '\033[48;2;@accent|rgbsp@m'   | tr ' ' ';')"

BRAND_GLYPH="@brand_glyph@"
BRAND_TEXT="@brand_text@"
