#@!out=/etc/auros/console.sh mode=0755
#!/bin/sh
# Generated by aurora — repaints the Linux virtual console palette.
# The kernel console understands OSC P<n><rrggbb>; this makes the TTY
# match the desktop exactly, so there is no jarring seam at boot.
[ -t 1 ] || exit 0
case "${TERM:-}" in linux|linux-*) ;; *) exit 0 ;; esac
printf '\033]P0@ansi0|hex@'
printf '\033]P1@ansi1|hex@'
printf '\033]P2@ansi2|hex@'
printf '\033]P3@ansi3|hex@'
printf '\033]P4@ansi4|hex@'
printf '\033]P5@ansi5|hex@'
printf '\033]P6@ansi6|hex@'
printf '\033]P7@ansi7|hex@'
printf '\033]P8@ansi8|hex@'
printf '\033]P9@ansi9|hex@'
printf '\033]PA@ansi10|hex@'
printf '\033]PB@ansi11|hex@'
printf '\033]PC@ansi12|hex@'
printf '\033]PD@ansi13|hex@'
printf '\033]PE@ansi14|hex@'
printf '\033]PF@ansi15|hex@'
# Clear so the new palette takes effect everywhere on screen.
printf '\033[H\033[2J'
