#@!out=/etc/auros/grub/theme.txt mode=0644
# Generated by aurora — GRUB2 gfxmenu theme.
title-text: ""
desktop-color: "#@bg|hex@"
terminal-font: "Unifont Regular 16"
terminal-box: "terminal_*.png"

+ boot_menu {
    left   = 22%
    top    = 34%
    width  = 56%
    height = 42%
    item_font           = "Unifont Regular 16"
    item_color          = "#@subtle|hex@"
    selected_item_color = "#@accent|hex@"
    item_height         = 28
    item_spacing        = 8
    item_padding        = 10
    selected_item_pixmap_style = "select_*.png"
}

+ label {
    left  = 0
    top   = 22%
    width = 100%
    align = "center"
    text  = "@brand_text@"
    color = "#@accent|hex@"
    font  = "Unifont Regular 16"
}

+ label {
    left  = 0
    top   = 84%
    width = 100%
    align = "center"
    text  = "@theme_name@"
    color = "#@muted|hex@"
    font  = "Unifont Regular 16"
}

+ progress_bar {
    id       = "__timeout__"
    left     = 32%
    top      = 78%
    width    = 36%
    height   = 4
    show_text = false
    bg_color = "#@overlay|hex@"
    fg_color = "#@accent|hex@"
}
