#@!out=/etc/auros/gtk/gtk.css mode=0644
/* Generated by aurora. Shared by GTK3 and GTK4 via @import.
   Present so third-party GTK apps land inside the theme instead of
   punching a bright hole in it. */
@define-color bg            @bg@;
@define-color bg_alt        @bg_alt@;
@define-color surface       @surface@;
@define-color surface_hi    @surface_hi@;
@define-color overlay       @overlay@;
@define-color muted         @muted@;
@define-color subtle        @subtle@;
@define-color fg            @fg@;
@define-color fg_hi         @fg_hi@;
@define-color accent        @accent@;
@define-color accent_alt    @accent_alt@;
@define-color warn          @warn@;
@define-color err           @err@;

@define-color theme_bg_color         @bg@;
@define-color theme_fg_color         @fg@;
@define-color theme_base_color       @surface@;
@define-color theme_selected_bg_color @accent@;
@define-color theme_selected_fg_color @accent|on@;
@define-color borders                @overlay@;

* {
  outline-color: @accent|rgba:0.55@;
  -gtk-secondary-caret-color: @accent@;
}

window, .background { background-color: @bg@; color: @fg@; }

headerbar {
  background: linear-gradient(@bg_alt@, @bg_alt|darken:6@);
  border-bottom: 1px solid @overlay@;
  color: @fg_hi@;
  min-height: @bar_height|int@px;
  padding: 0 @padding|int@px;
}

button {
  background: @surface@;
  color: @fg@;
  border: 1px solid @overlay@;
  border-radius: @radius_sm|int@px;
  padding: 6px 14px;
  transition: background @animation_ms|int@ms ease, border-color @animation_ms|int@ms ease;
}
button:hover        { background: @surface_hi@; border-color: @accent|rgba:0.45@; }
button:active       { background: @surface_hi|darken:12@; }
button:disabled     { color: @muted@; background: @surface|darken:4@; }
button.suggested-action {
  background: @accent@; color: @accent|on@; border-color: @accent|darken:12@;
}
button.destructive-action { background: @err@; color: @err|on@; }

entry {
  background: @bg@;
  color: @fg_hi@;
  border: 1px solid @overlay@;
  border-radius: @radius_sm|int@px;
  padding: 7px 12px;
  caret-color: @accent@;
}
/* A thicker border, not a halo. box-shadow: 0 0 0 2px <accent 22%>
 * is a glow ring, and it was the only one of those the system pushed
 * into third-party apps. A 2px solid edge says the same thing, works
 * on a light theme, and does not blur. */
entry:focus { border-color: @accent@; border-width: 2px; padding: 6px 11px; }

list, treeview { background: @bg@; color: @fg@; }
row:selected, treeview:selected { background: @accent@; color: @accent|on@; }
row:hover { background: @surface_hi@; }

scrollbar slider {
  background: @overlay|lighten:10@;
  border-radius: 8px;
  min-width: 7px; min-height: 7px;
}
scrollbar slider:hover { background: @accent|rgba:0.65@; }

popover, menu, .menu {
  background: @surface@;
  border: 1px solid @overlay@;
  border-radius: @radius|int@px;
  padding: 6px;
}

tooltip {
  background: @surface_hi@;
  color: @fg_hi@;
  border-radius: @radius_sm|int@px;
  border: 1px solid @overlay@;
}

progressbar progress { background: @accent@; border-radius: 4px; }
switch:checked       { background: @accent@; }
check:checked, radio:checked { background: @accent@; border-color: @accent@; }
separator { background: @overlay@; }
selection { background: @accent|rgba:0.35@; color: @fg_hi@; }

/* ── one title bar, not two ─────────────────────────────────────────
 *
 * AurOS's archetypes draw a window's title and its close button
 * themselves, in the theme's colours, at a size docs/EASY.md says she
 * can press. GTK3 ALSO draws a title bar for any window that has none
 * of its own -- which is every application this product ships, since
 * they all use a menu bar rather than a header bar.
 *
 * So a file manager came up with two title bars, two titles and two
 * close buttons, one of them small and grey. "Which X do I press?" is
 * not a question this product may ask her. Seen by booting the image
 * and opening the file manager.
 *
 * Only GTK's FALLBACK bar is collapsed: `.default-decoration` is the
 * class GTK puts on the one it invents. A real header bar carries the
 * application's own controls -- its search, its menu -- and is left
 * exactly alone.
 *
 * GTK's CSS has no way to hide a widget, so it is flattened instead:
 * no height, no padding, nothing drawn, and its contents given no size
 * of their own.
 */
window.csd > .titlebar.default-decoration,
window.solid-csd > .titlebar.default-decoration {
  min-height: 0;
  padding: 0;
  margin: 0;
  border: none;
  box-shadow: none;
  background: none;
}
window.csd > .titlebar.default-decoration > *,
window.solid-csd > .titlebar.default-decoration > * {
  min-height: 0;
  min-width: 0;
  padding: 0;
  margin: 0;
  opacity: 0;
}
window.csd > .titlebar.default-decoration button.titlebutton,
window.solid-csd > .titlebar.default-decoration button.titlebutton {
  min-height: 0;
  min-width: 0;
  padding: 0;
  margin: 0;
  border: none;
  background: none;
  opacity: 0;
}
