#@!out=/etc/auros/prompt.sh mode=0644
# Generated by aurora — the AurOS shell prompt.
# A single accent-coloured rule, the path, and a glyph. Nothing else:
# the prompt should recede, not compete with the output above it.
. /etc/auros/colors.sh 2>/dev/null || true

__auros_prompt() {
    _rc=$?
    _p=${PWD#"$HOME"}
    [ "$_p" != "$PWD" ] && _p="~$_p"
    if [ "$_rc" -ne 0 ]; then
        _glyph="${C_ERR}@brand_glyph@${C_RESET}"
    else
        _glyph="${C_ACCENT}@brand_glyph@${C_RESET}"
    fi
    if [ "$(id -u)" = 0 ]; then
        _who="${C_ACCENT_WARM}root${C_RESET}${C_MUTED}:${C_RESET}"
    else
        _who=""
    fi
    printf '\n%s%s%s %s\n%s ' \
        "${C_SUBTLE}" "$_p" "${C_RESET}" "$_who" "$_glyph"
}
PS1='$(__auros_prompt)'
PS2="${C_MUTED}  … ${C_RESET}"
export PS1 PS2
