#@!out=/etc/auros/shell.conf mode=0644
# Generated by aurora. Do not edit — edit the theme and re-run `aurora set`.
# aurshell re-reads this on SIGHUP, so retheming never needs a recompile.

theme_name        = @theme_name@
theme_variant     = @theme_variant@

# ── Geometry ───────────────────────────────────────────────
bar_height        = @bar_height|int@
radius            = @radius|int@
radius_sm         = @radius_sm|int@
gap               = @gap|int@
margin            = @margin|int@
border            = @border|int@
padding           = @padding|int@

# ── Colours (0xRRGGBB) ─────────────────────────────────────
col_bg            = @bg|0x@
col_bg_alt        = @bg_alt|0x@
col_surface       = @surface|0x@
col_surface_hi    = @surface_hi|0x@
col_overlay       = @overlay|0x@
col_muted         = @muted|0x@
col_subtle        = @subtle|0x@
col_fg            = @fg|0x@
col_fg_hi         = @fg_hi|0x@
col_accent        = @accent|0x@
col_accent_alt    = @accent_alt|0x@
col_accent_warm   = @accent_warm|0x@
col_ok            = @ok|0x@
col_warn          = @warn|0x@
col_err           = @err|0x@
col_info          = @info|0x@

# Derived shades the shell would otherwise have to guess at.
col_bar_bg        = @bg_alt|mix:bg:20|0x@
col_focus_glow    = @accent|lighten:18|0x@
col_press         = @surface_hi|darken:12|0x@
col_on_accent     = @accent|on|0x@
col_scrollbar     = @overlay|lighten:10|0x@

# ── Terminal ANSI ──────────────────────────────────────────
ansi0 = @ansi0|0x@
ansi1 = @ansi1|0x@
ansi2 = @ansi2|0x@
ansi3 = @ansi3|0x@
ansi4 = @ansi4|0x@
ansi5 = @ansi5|0x@
ansi6 = @ansi6|0x@
ansi7 = @ansi7|0x@
ansi8 = @ansi8|0x@
ansi9 = @ansi9|0x@
ansi10 = @ansi10|0x@
ansi11 = @ansi11|0x@
ansi12 = @ansi12|0x@
ansi13 = @ansi13|0x@
ansi14 = @ansi14|0x@
ansi15 = @ansi15|0x@

# ── Effects ────────────────────────────────────────────────
blur              = @blur|int@
blur_radius       = @blur_radius|int@
shadow            = @shadow|int@
shadow_opacity    = @shadow_opacity@
shadow_radius     = @shadow_radius|int@
opacity_panel     = @opacity_panel@
opacity_inactive  = @opacity_inactive@
animation_ms      = @animation_ms|int@
animation_curve   = @animation_curve@

# ── Typography ─────────────────────────────────────────────
# Three faces, not one. `font_display` is set large and `font_text`
# small; the contrast between them is the hierarchy, which is why
# there is no display slot in a system that had only one face.
font_display      = /usr/share/auros/fonts/@font_display@.ttf
font_text         = /usr/share/auros/fonts/@font_text@.ttf
font_text_bold    = /usr/share/auros/fonts/@font_text_bold@.ttf
font_sans         = /usr/share/auros/fonts/@font_sans@.ttf
font_mono         = /usr/share/auros/fonts/@font_mono@.ttf
font_size         = @font_size|int@
font_size_sm      = @font_size_sm|int@
font_size_lg      = @font_size_lg|int@
line_height       = @line_height@

# ── Wallpaper ──────────────────────────────────────────────
wall_style        = @wall_style@
wall_c1           = @wall_c1|0x@
wall_c2           = @wall_c2|0x@
wall_c3           = @wall_c3|0x@
wall_c4           = @wall_c4|0x@
wall_intensity    = @wall_intensity@
wall_grain        = @wall_grain@
wall_vignette     = @wall_vignette@

# ── Branding ───────────────────────────────────────────────
brand_glyph       = @brand_glyph@
brand_text        = @brand_text@
cursor_size       = @cursor_size|int@
