# GENERATED by recipes/bin/auros-recipe from an organisation recipe. Do not edit:
#   change the recipe, then: recipes/bin/auros-recipe compile <recipe> -o profiles/<name>.profile
#   what it installs and removes, in plain words: recipes/bin/auros-recipe explain <recipe>
inherit="desktop"

# ── who these machines are for ────────────────────────────────────────
# name: example-kiosk
profile_id="example-kiosk"
# organisation.display_name: Example Community Services
profile_name="Example Community Services"
brand_name="Example Community Services"
# for: (shown by `build/forge list`)
profile_description="Forty counter kiosks across six walk-in service centres. A visitor sits down, uses the benefits and job-search sites, prints what they need, and walks away. Nobody signs in and nothing on the machine can be changed by the person using it."

# ── language, keyboard, clock ─────────────────────────────────────────
# language: English (United States)
locale="en_US.UTF-8"
# other_languages: (none)
extra_locales=""
# keyboard: English (US)
keyboard_layout="us"
keyboard_variant=""
# switch_scripts_with: (no second layout)
keyboard_options=""
# timezone: America/Los_Angeles
timezone="America/Los_Angeles"

# ── programs ──────────────────────────────────────────────────────────
# apps: Firefox
# prune.keep_only_the_apps_above: true
packages_apps=""
# the standard desktop's programs that stay (desktop.profile packages_files, minus what is removed)
packages_files="shared-mime-info desktop-file-utils xdg-user-dirs"
# desktop.profile packages_hardware, minus: bluetooth
packages_hardware="linux-image-generic linux-firmware network-manager wireless-tools wpasupplicant polkitd cups cups-filters cups-browsed avahi-daemon avahi-utils printer-driver-gutenprint printer-driver-hpcups cups-pk-helper system-config-printer pciutils usbutils"
# what English (United States) needs: translations, and fonts for scripts the base fonts cannot draw
packages_extra="language-pack-en"
# no Software Centre on these machines
software_store="none"

# ── policy: kiosk ─────────────────────────────────────────────────────
# A machine on a counter. There is no desktop: the first program starts by itself and fills the screen, nobody signs in, and nothing can be changed, installed, mounted or reached from it.
kiosk_mode="yes"
allow_user_install="no"
allow_settings_change="no"
allow_theme_change="no"
allow_network_change="no"
allow_tty="no"
# only these programs exist for the person at the machine; Firefox starts by itself
allowed_apps="firefox"
# policy: kiosk is the locked shell
shell_archetype="locked"
