# GENERATED by recipes/bin/auros-recipe from an organisation recipe. Do not edit:
#   change the recipe, then: recipes/bin/auros-recipe compile <recipe> -o profiles/<name>.profile
#   what it installs and removes, in plain words: recipes/bin/auros-recipe explain <recipe>
inherit="desktop"

# ── who these machines are for ────────────────────────────────────────
# name: example-workstation
profile_id="example-workstation"
# organisation.display_name: Example Studio
profile_name="Example Studio"
brand_name="Example Studio"
# for: (shown by `build/forge list`)
profile_description="One developer desktop belonging to the person who maintains these recipes. It keeps the ordinary desktop and adds a working set on top rather than being stripped to a handful of programs, and it is the only machine in these examples with a command line."

# ── language, keyboard, clock ─────────────────────────────────────────
# language: English (United Kingdom)
locale="en_GB.UTF-8"
# other_languages: (none)
extra_locales=""
# keyboard: English (UK)
keyboard_layout="gb"
keyboard_variant=""
# switch_scripts_with: (no second layout)
keyboard_options=""
# timezone: Europe/London
timezone="Europe/London"

# ── programs ──────────────────────────────────────────────────────────
# apps: Files, Firefox, GIMP, Image Viewer, Inkscape, Kate, Konsole, Text Editor
# prune.keep_only_the_apps_above: false
packages_apps="gimp inkscape kate konsole"
# what English (United Kingdom) needs: translations, and fonts for scripts the base fonts cannot draw
packages_extra="language-pack-en"
# Software Centre: part of the standard desktop
software_store="gnome-software"

# ── policy: open ──────────────────────────────────────────────────────
# The person at the machine owns it: they may install programs, change settings and the look, choose the wifi, and reach a console.
kiosk_mode="no"
allow_user_install="yes"
allow_settings_change="yes"
allow_theme_change="yes"
allow_network_change="yes"
# desktop.can_reach_a_terminal: true
allow_tty="yes"
# empty: everything installed may be opened
allowed_apps=""
# desktop.layout: workbench
shell_archetype="workbench"

# ── look ──────────────────────────────────────────────────────────────
# theme: ember (dark)
theme="ember"
