# GENERATED by recipes/bin/auros-recipe from an organisation recipe. Do not edit:
#   change the recipe, then: recipes/bin/auros-recipe compile <recipe> -o profiles/<name>.profile
#   what it installs and removes, in plain words: recipes/bin/auros-recipe explain <recipe>
inherit="desktop"

# ── who these machines are for ────────────────────────────────────────
# name: example-school
profile_id="example-school"
# organisation.display_name: Example Vidyalaya
profile_name="Example Vidyalaya"
brand_name="Example Vidyalaya"
# for: (shown by `build/forge list`)
profile_description="The 180 shared classroom laptops at a Marathi-medium secondary school. Pupils sign in to Google Workspace in the browser and do all their work there. Teachers use the same laptops. Nobody installs anything by hand on these machines."

# ── language, keyboard, clock ─────────────────────────────────────────
# language: Marathi
locale="mr_IN.UTF-8"
# other_languages: English (India), Hindi
extra_locales="en_IN.UTF-8 hi_IN.UTF-8"
# keyboard: English (US); second_script: Marathi (InScript)
keyboard_layout="us,in"
keyboard_variant=",marathi"
# switch_scripts_with: Windows key + Spacebar
keyboard_options="grp:win_space_toggle"
# timezone: Asia/Kolkata
timezone="Asia/Kolkata"

# ── programs ──────────────────────────────────────────────────────────
# apps: Calculator, Document Viewer, Files, Firefox, GCompris, Image Viewer, Text Editor, Tux Paint, Typing Tutor, VLC Media Player
# prune.keep_only_the_apps_above: true
packages_apps="gcompris-qt tuxpaint klavaro vlc"
# the standard desktop's programs that stay (desktop.profile packages_files, minus what is removed)
packages_files="thunar thunar-volman gvfs gvfs-backends udisks2 ristretto atril mousepad mate-calc shared-mime-info desktop-file-utils xdg-user-dirs"
# desktop.profile packages_hardware, minus: bluetooth
packages_hardware="linux-image-generic linux-firmware network-manager wireless-tools wpasupplicant polkitd cups cups-filters cups-browsed avahi-daemon avahi-utils printer-driver-gutenprint printer-driver-hpcups cups-pk-helper system-config-printer pciutils usbutils"
# what English (India), Hindi, Marathi need: translations, and fonts for scripts the base fonts cannot draw
packages_extra="fonts-noto-core language-pack-en language-pack-hi language-pack-mr"
# no Software Centre on these machines
software_store="none"

# ── policy: managed ───────────────────────────────────────────────────
# Somebody responsible for many machines decides what is installed. The person using one still decides how it looks and behaves, and may choose the wifi.
kiosk_mode="no"
allow_user_install="no"
allow_settings_change="yes"
allow_theme_change="yes"
allow_network_change="yes"
allow_tty="yes"
# empty: everything installed may be opened
allowed_apps=""
# desktop.layout: dock
shell_archetype="dock"

# ── look ──────────────────────────────────────────────────────────────
# theme: sandstone (light)
theme="sandstone"
