# musl — the C library AurOS is built against.
#
# Chosen over glibc deliberately: it is small enough to read, statically
# links cleanly, and keeps the base system under a few megabytes.
pkgname=musl
pkgver=1.2.4
pkgdesc="Lightweight, fast, standards-conformant C library"
license="MIT"
url="https://musl.libc.org"
source="musl-1.2.4.tar.gz"
sha256="7a35eae33d5372a7c0da1188de798726f68825513b7ae3ebe97aaaa52114f039"
depends=""
provides="libc"

build() {
    cd "$srcdir/musl-$pkgver"
    # --prefix=/usr is the path inside the target system. The host-side
    # toolchain copy gets its spec paths rewritten in package().
    ./configure \
        --prefix=/usr \
        --syslibdir=/lib \
        --enable-wrapper=gcc \
        --disable-gcc-wrapper
    make -j"$JOBS"
}

package() {
    cd "$srcdir/musl-$pkgver"
    make DESTDIR="$pkgdir" install

    # Also stage into the sysroot so every later package links against
    # musl rather than the host glibc.
    make DESTDIR="$SYSROOT" install

    # musl-gcc.specs is generated with the target's absolute paths. For
    # the host-side wrapper those must point into the sysroot instead —
    # except the dynamic-linker path, which is a target runtime path and
    # must stay /lib/ld-musl-*.so.1.
    mkdir -p "$SYSROOT/bin"
    sed -e "s|-isystem /usr/include|-isystem $SYSROOT/usr/include|g" \
        -e "s|-L/usr/lib|-L$SYSROOT/usr/lib|g" \
        -e "s| /usr/lib/| $SYSROOT/usr/lib/|g" \
        "$SYSROOT/usr/lib/musl-gcc.specs" > "$SYSROOT/usr/lib/musl-gcc-host.specs"

    cat > "$SYSROOT/bin/musl-gcc" <<WRAP
#!/bin/sh
# Generated by the musl recipe. Redirects the host gcc at the AurOS
# sysroot so nothing accidentally links against host glibc.
exec "\${REALGCC:-gcc}" "\$@" -specs "$SYSROOT/usr/lib/musl-gcc-host.specs"
WRAP
    chmod +x "$SYSROOT/bin/musl-gcc"

    # The dynamic loader is the same file as libc.so; ship the symlink
    # the ELF interpreter path actually names.
    mkdir -p "$pkgdir/lib"
    [ -e "$pkgdir/lib/ld-musl-x86_64.so.1" ] || \
        ln -sf ../usr/lib/libc.so "$pkgdir/lib/ld-musl-x86_64.so.1"
}
